# Generated by Django 3.2.3 on 2021-05-20 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('quizzes', '0003_quiz_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='achievement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.achievement'),
        ),
    ]
