# Generated by Django 3.2.3 on 2021-05-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quiz_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='pass_mark',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
