# Generated by Django 3.2.3 on 2021-05-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quiz_pass_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='linked_quizzes',
            field=models.ManyToManyField(blank=True, related_name='_quizzes_quiz_linked_quizzes_+', to='quizzes.Quiz'),
        ),
    ]
