# Generated by Django 3.2 on 2021-05-03 12:36

from django.db import migrations, models
import files.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('code', models.CharField(db_index=True, default=files.utils.generate_random_url, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(db_index=True, default=files.utils.generate_random_url, max_length=255, unique=True)),
                ('articles', models.ManyToManyField(to='core.Article')),
                ('files', models.ManyToManyField(to='files.File')),
            ],
        ),
    ]
