# Generated by Django 3.2 on 2021-05-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        ('core', '0002_auto_20210512_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='quizzes',
            field=models.ManyToManyField(to='quizzes.Quiz'),
        ),
    ]
