# Generated by Django 3.2 on 2021-05-02 12:02

from django.db import migrations, models
import files.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=files.utils.generate_random_url, max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('COMIC', 'Comic'), ('VIDEO', 'Video')], default='VIDEO', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
